### ISSUE TITLE
claimedDuplicateSegments() slashing condition

### ISSUE THREAD

**Issue by dob** [livepeer/protocol#106]
As mentioned in #99, a short term solution for preventing a transcoder from claiming a segment twice is to add a slashing condition. A watcher can call

`claimedDuplicateSegments(segmentNumber, claimID1, claimID2)`

The code could check the segment ranges on those two claims and if the segmentNumber appeared in both, it would enact the slashing condition.

We want to prevent this from getting invoked twice. And we should also consider whether other claims for the same job would be eligible for payout or slashable.

**Comment by yondonfu** [comment]
I think it might make sense for a transcoder to automatically be kicked out of the active transcoder set (so it wouldn't be able to get the payouts for any other claims) and for the broadcaster to be fully refunded for this slashing condition. In the missed verification slashing condition a transcoder might be unable to submit a segment for verification due to network congestion. In the failed verification slashing condition a transcoder might fail due to issues with the verification solution being used. In both cases, the transcoder could actually be honest. With this claimed duplicate segments slashing condition, the intent to cheat seems pretty clear if a transcoder claims work for a segment more than once.
