### ISSUE TITLE
Job routing is always routing jobs to highest staked transcoder and not routing proportionally

### ISSUE THREAD

**Issue by dob** [livepeer/protocol#147]
Currently on testnet the transcoder delegation looks like this:

```
+----------------------+
|REGISTERED TRANSCODERS|
+----------------------+
+----+--------------------------------------------+--------+------------------------------+----------------+---------------+-------+------------------------+-----------------------+---------------+
| ID |                  ADDRESS                   | ACTIVE |       DELEGATED STAKE        | REWARD CUT (%) | FEE SHARE (%) | PRICE | PENDING REWARD CUT (%) | PENDING FEE SHARE (%) | PENDING PRICE |
+----+--------------------------------------------+--------+------------------------------+----------------+---------------+-------+------------------------+-----------------------+---------------+
|  0 | 0xFeBF35b94e16E018Ab5cA9aA1f66aaC1a1AB29E0 | true   | 69828.859299524624845138 LPT |             20 |            10 | 5 WEI |                     20 |                    10 | 5 WEI         |
|  1 | 0x97Ab31E8E0BE434CdD02a0C017266894E81Cdd82 | true   | 69646.494846492990017785 LPT |             10 |             5 | 1 WEI |                     10 |                     5 | 1 WEI         |
|  2 | 0x102551aDEaC5b4d043b6B2423e774dc3Db004031 | true   | 43664315968921069 LPTU       |             10 |             5 | 1 WEI |                     10 |                     5 | 1 WEI         |
+----+--------------------------------------------+--------+------------------------------+----------------+---------------+-------+------------------------+-----------------------+---------------+
```

A local broadcaster has his broadcasting profile set to offer 10 LPT/segment. The jobs should roughly be split between transcoders 0 and 1, but all jobs are being routed to transcoder 0.

**Comment by yondonfu** [comment]
So after some investigation I don't think the job assignment contract logic is the root of the problem. Currently, when a transcoder node receives a new job event, it will call the read only contract function `electActiveTranscoder(jobPrice, jobCreationBlock, jobCreationRound)` to determine whether or not it was assigned to the job. `block.blockhash(jobCreationBlock)` is used as the pseudorandom seed for the weighted job assignment logic. `block.blockhash` will return `0x0` if the block number is more than 256 blocks in the past or if the block number is the block the function call is executing within (not possible to know the hash at this point) or if the block number is in the future. If the transcoder node checks if it is assigned in the block right after the `jobCreationBlock`, when it calls `electActiveTranscoder`, the read only function executes locally so from the contract's point of view `jobCreationBlock` == the block that the function call is executing within. As a result, `block.blockhash` will return `0x0`. This is in contrast to if `electActiveTranscoder` was a state mutating transaction - in this case, `jobCreationBlock` == the block BEFORE the block that the function call is executing within because transactions run in the pending block as opposed to the latest block in the chain.

Some possible solutions:
1) The transcoder node waits an extra block before checking if it was assigned. This is not ideal since this adds extra wait time before any transcoding begins so this is probably not the way to go.
2) The transcoder node computes off-chain the exact algorithm implemented in `electActiveTranscoder` thereby avoiding the issue with using `block.blockhash` in a read only contract function.
3) Modify `electActiveTranscoder` to accept the job creation block hash instead of the job creation block. The transcoder node would retrieve the block hash and pass it in directly to `electActiveTranscoder` instead of relying on the contract to retrieve it with `block.blockhash`. A transcoder has control of the hash passed in, but if it passed in the wrong hash, it will fail the `electActiveTranscoder` check when it calls `claimWork` for the first time because `claimWork` will use `block.blockhash` to retrieve the hash for the job creation block (note: we can retrieve the hash just fine here because `electActiveTranscoder` is called as a part of the `claimWork` transaction and is not executed locally as a read only function).

I think 3 would just require a few minor changes so I'm going to work with that first.

**Comment by dob** [comment]
Awesome work investigating this one. I agree that 2 or 3 is the best solution, with 3 keeping the most consistency in the on/off chain implementations.

________________________________
