### ISSUE TITLE
On-chain price signaling for a user that is campaigning to become a transcoder

### ISSUE THREAD

**Issue by yondonfu** [livepeer/protocol#191]
At the moment, we prevent users from registering as a transcoder if the transcoder pool is full and they have insufficient delegated stake to evict the transcoder in the pool with the lowest delegated stake. As a result, these users have to campaign off-chain to have other users delegate tokens towards them (effectively as "sponsors") in order to build up enough delegated stake to eventually join the transcoder pool. 

A question is whether the protocol should allow these users to invoke the `transcoder` function to just set the `rewardCut`, `feeShare` and `pricePerSegment` that the user *would* charge if it was a registered transcoder as a form of on-chain price signaling. The benefits of this are 1) increased transparency 2) queryable on-chain data to build a dapp interface for delegating to users that are campaigning to become transcoders. The potential disadvantages of this are 1) data management is less clean because you end up with transcoder data structures that have some fields populated, but are not registered while the alternative is to ensure that all fields in a transcoder data structure are zeroed out if the user is not registered.

**Comment by jozanza** [comment]
I'm in favor of allowing users to invoke `transcoder` because it will allow visibility into campaigns more readily. We can easily add a list into the explorer app. Otherwise, we have at least two options I can think of immediately:

We could not put this feature into any app and constantly refer folks to the forum, which can certainly display campaign information, but discovering/filtering/sorting will be poor.

Alternatively, we could have to introduce some sort of persistence layer that allows these campaigners to signal their campaign information. Some potential options could be 1) a centralized db, 2) another set of smart contracts/ENS, 3) or some peer messaging (maybe libp2p in browser clients or perhaps via Livepeer nodes).

**Comment by j0sh** [comment]
Would this make it more expensive to initialize a round (or run certain other operations) if the contract has to sift through transcoders that are still outside the pool threshold?

Allowing transcoders to set the cuts/fees/price is the lowest friction way for delegators to discover transcoders (eg, via MetaMask). That alone justifies the effort IMO. There might still be some form of centralized location/registry where transcoders can supply more information for delegators, but this takes the basic question of transparency out of that equation.

**Comment by yondonfu** [comment]
Allowing for price signaling by non-registered transcoders would not increase the cost of initializing a round since these users would not be in the transcoder pool at all - it would purely for letting users declare to everyone what prices they *would* charge on-chain . I agree that the transparency and decreased cost of coordination by having this data available on-chain can be useful
