### ISSUE TITLE
Enhance transcoder() function to include job parameters.

### ISSUE THREAD

**Issue by dob** [livepeer/protocol#20]
Enhance the `transcoder()` function to include `_feeShare` and `_pricePerSegment`.

In the future we will want to use gas accounting rather than a flat `_pricePerSegment`, but for now this is a reasonable starting point.

`_feeShare` should be given as a percent. For example, if they pass it in as `5`, then they will share 5% of the fees with their delegators.

`_pricePerSegment` can be given in LPT base units (we need a name for that since 1 LPT == 10^18 base units).

**Comment by yondonfu** [comment]
Regarding a name for LPT base units - is that something that should be defined at the token/protocol contract level? Since the token contract already defines `decimals`, perhaps a name for LPT base units can be something that is defined by the community at a later point in time? Maybe there will end up being different thresholds as well similar to Ether (i.e. wei, finney, etc.)

**Comment by dob** [comment]
Correct, it's only convention and isn't strictly defined within the
protocol. It'll just make it easier for us to pronounce: 10,000 dovens vs
10 * 10^-15 LPT.

**Comment by yondonfu** [comment]
Closed by #29
