### ISSUE TITLE
Job() request transaction

### ISSUE THREAD

**Issue by dob** [livepeer/protocol#22]
The `job()` function is how broadcasters request transcoding jobs on chain. The inputs are:

* streamID
* transcoding options
* max price/segment

`streamID` lets the transcoding node know which stream to request on the network

transcoding option semantics are TBD. Let's assume it's a binary string of fixed length for now, and we can interpret it as 0x1, 0x2, etc, without use. 

The function should consider all transcoders who are currently available and are charging a price/segment less than or equal to the max price/segment provided, and choose one (hopefully randomly). The function should populate the metadata associated with a `Job` and store this so that the contract knows what jobs are open, who they are assigned to, and what they're status is in terms of claiming the work and verification. This likely requires a new `Job` struct. Jobs can also be assigned a unique ID so that they can be retrieved from the contract by ID.

**Comment by yondonfu** [comment]
Some thoughts on considering transcoders that are currently available and charging a price/segment less than or equal to the max price/segment.

In order to avoid the use of additional loops, what if we keep track of an `availableTranscoders` array for a `Job` struct. There would be some timedelta within which current active transcoders can call `transcoderAvailability()` for a particular job which would add the transcoder to `availableTranscoders`, but only if the `transcoders[msg.sender].pricePerSegment <= job.maxPricePerSegment`. After the timedelta, the broadcaster can call `startJob(jobId)` and the function will pseudorandomly select a transcoder from `availableTranscoders` for the job. If a transcoder is unresponsive, a broadcaster can call `startJob(jobId)` again to select a different transcoder from `availableTranscoders`.

**Comment by dob** [comment]
Right now I like that in our protocol a broadcaster only needs one on-chain call in the whole workflow (I think). Adding a second `startJob()` call would double the fees and add another confirmation period before they could start broadcasting. It's also nice that transcoders can just declare their availability once, rather than having to offer availability for each additional job (many of which they won't receive).

Are you trying to avoid looping over the availableTranscoders to compare their prices on every job? I wonder if it's more efficient to randomly select, and then check for availability and price? If we assume that transcoders are largely available and looking for work, then in the worst case this becomes the same as a loop, but in the avg case it avoids doing a loop and finds a hit in some much more efficient frequency.

**Comment by yondonfu** [comment]
Closed by #30
