### ISSUE TITLE
When a delegator switches bonding transcoder, please log previously bonded transcoder.

### ISSUE THREAD

**Issue by chunxi** [livepeer/protocol#224]
A delegator has bonded to transcoder A. In later round, it bonds to transcoder B. When this happens, a `Bond` event is logged with transcoder B. Transcoder A is unbonded, its stake has changed, but is not logged in any event. In order to accurately track stake changes of transcoders. Please log previously bonded transcoder. Thanks!

**Comment by dob** [comment]
So the solution here is adding the previous transcoder address to the Bond event.

Do we view adding a field to an event as a backwards compatibility breaking change? On the client/parsing side I assume clients would be able to parse the fields they want out of an event, so an additional field wouldn't break clients? Though they may need to be upgraded to make use of the new data.

@yondonfu do you think we need an LIP for changes to events?

**Comment by yondonfu** [comment]
> Do we view adding a field to an event as a backwards compatibility breaking change?

Since most clients will be using static contract ABI files, adding a field to an event would be a backwards incompatible change for clients because the additional field would change the event signature hash from `keccak256("Bond(address,address)")` to `keccak256("Bond(address,address,address)")` - as a result, clients wouldn't be able to create a filter for the event anymore since they do not know how to generate the updated event signature hash. Clients would need to upgrade to use the new contract ABI files so that whatever library they are using for contract event encoding/decoding can do so using the new event definitions.

> do you think we need an LIP for changes to events?

I imagine in the future it definitely would require one because it not only requires a contract upgrade, but is also a backwards incompatible change for clients. I can see the argument for adhering to the process for *any* contract change today to have the LIPs always reflect the history of included contract changes, however, in this current alpha stage in the interest of moving quicker I would be ok with forgoing the LIP since there are only 2 clients (known) maintained by the same entity and the change does not modify the dynamics of the protocol and only logs some additional data. What do you think?

**Comment by dob** [comment]
Yah, sounds like getting in the habit of quick and easy LIPs for things like this is good, so that everything is documented and can be organized into a single release.

**Comment by yondonfu** [comment]
Hey @chunxi I created a proposal to update this event here: https://github.com/livepeer/LIPs/pull/11 Feel free to hop in and point out if anything is missing for your use case!

**Comment by chunxi** [comment]
@yondonfu How do I know if this gets live on mainnet?

**Comment by yondonfu** [comment]
@chunxi We'll make an announcement in various channels (i.e. forum, Twitter, etc.) detailing what proposals are included in a mainnet upgrade and we can ping you then as well

**Comment by yondonfu** [comment]
Hey @chunxi this change is now live on mainnet!

See here for the updated event signature: https://github.com/livepeer/protocol/blob/master/contracts/bonding/IBondingManager.sol#L14

If you happen to still need to filter for the old event signature you can still do so. Here is a simple example using web3.js:

```
    // Filter for deprecated event Bond(address indexed delegate, address indexed delegator)
    const oldBondFilter = {
        fromBlock: initBlock,
        address: bondingManagerAddr,
        topics: [
            web3.utils.sha3("Bond(address,address)"),
            null, // If you want to filter for a specific delegate address, add the address here
            null // If you want to filter for a specific delegator address, add the address here
        ]
    }

    const oldBondLogs = await web3.eth.getPastLogs(oldBondFilter)
```

Since this is now live on mainnet, I'm going to close this issue, but if you have any additional questions or concerns let's talk about them on Discord!
