### ISSUE TITLE
Functions visibility are public in SortedDoublyLL library

### ISSUE THREAD

**Issue by gjgd** [livepeer/protocol#226]
https://github.com/livepeer/protocol/blob/master/contracts/libraries/SortedDoublyLL.sol#L40

Shouldn't all library functions have an `internal` visibility ?

**Comment by yondonfu** [comment]
Not necessarily - `internal` library functions will be inlined into the calling contract's code at compile while `public` library functions will be invoked by a calling contract using the EVM `DELEGATECALL` opcode which will execute the library function logic in the context of the calling contract's storage (see: http://solidity.readthedocs.io/en/v0.4.24/contracts.html#libraries). One of the benefits of `public` library functions is reducing the bytecode size of the calling contract since it doesn't have to inline the library code.

**Comment by gjgd** [comment]
Oh I see, I wasn't aware of that distinction thanks.
