### ISSUE TITLE
Transcoder with Small Bond Becomes Permanently "Not Registered" in the Round After Creation

### ISSUE THREAD

**Issue by leopoldjoy** [livepeer/protocol#276]
When a new transcoder is created by invoking the multi-step "become a transcoder" process from the CLI (while bonding an insufficient amount of LPT to become active), the transcoder initially has the status of "Registered." However, if no additional LPT token is bonded to the transcoder by the next round, the status changes to "Not Registered" and it becomes impossible to reregister the transcoder—unbonding/rebonding and even reinvoking the multi-step "become a transcoder" process all do not change the status back to "Registered."

I understand that bonding a sufficient amount of LPT token to the transcoder (enough to become "Active") will change the status back to "Registered" in the subsequent round. However, this unpredictable/inconsistent behaviour of the transcoder status property may lead to confusion, particularly for new transcoders.

**Comment by yondonfu** [comment]
I don't think this should be an issue anymore because the address will be considered as "Registered" as long as it is self-delegated and has > 0 stake [1] regardless of whether the address is active (i.e. has sufficient stake to be in the top 100). Closing for now, but feel free to re-open if this is still an issue.

[1] https://github.com/livepeer/protocol/blob/7bc8c30fe6b65d9f907f60fdb680be8101712b5f/contracts/bonding/BondingManager.sol#L1061
