### ISSUE TITLE
Repurpose transcoder registered status to reflect self-delegation as desire to be an transcoder

### ISSUE THREAD

**Issue by kyriediculous** [livepeer/protocol#304]
Since we're removing the notion of an `activeTranscoderSet` will become equal to simply being in the active set or not, as that check is currently whether the transcoder is in `transcoderPool`. 

A transcoder might still however be registered but not part of the active set for a round.  Therefore we need a different way to determine if a transcoder is registered if we are to use `transcoderPool` as the active transcoder set. 

We can treat self-delegation as desire to be a transcoder. This means Registered/Unregistred will be implicit based on a transcoder's own stake but in the current version of the protocol this is also implicit by being part of the `transcoderPool`. 

An alternative would be to add a flag to the `Transcoder` struct indicating registered status but that approach is less favorable.
- It changes the storage layout (even though the changes can be compatible, it seems reasonable to avoid doing it unless necessary). 
- It incurs additional SSTORE operations: registering would cost 20k gas extra (setting a zero storage slot to non-zero) and resigning would cost 5k gas more (setting a non-zero slot to zero)

**Comment by yondonfu** [comment]
> If a transcoder calls BondingManager.transcode() to set its rewardCut and feeShare we can consider the transcoder as Registered

We won't be able to rely on `rewardCut` and `feeShare` as indicators of a transcoder's registered status because those parameters could be set to 0. Some options to explore include:

- Treating self-delegation as a signal of a desire to be a transcoder
- Adding a flag to the `Transcoder` struct to indicate registered status
- Adding a `workerAddress` field to the `Transcoder` struct that indicates the address that can submit transactions for the registered transcoder

There might be more options, but just listing a few for now.

**Comment by kyriediculous** [comment]
I forgot to mention adding a flag to `Transcoder` . But after letting it sit for the night I seem to be more in favor of self-delegation as a desire to be a transcoder. 

I have updated the original issue to reflect this better and added a reasoning for the preference.

**Comment by yondonfu** [comment]
Closed by #323
