### ISSUE TITLE
Transaction error "Fail with error 'too many rounds to claim through'"

### ISSUE THREAD

**Issue by HydraGene** [livepeer/protocol#392]
I get a transaction error when claiming rounds at https://explorer.livepeer.org/

I get 3 transaction requests. Is this normal? In the past I always had just one request..
First one fails right away, second one fails sometimes and is sometimes pending, and third one is pending and after a while I get the error "Fail with error 'too many rounds to claim through'"

Transaction ID: 0x1f6bd9d2e94a3a166aa8cdd40c537b3e4d1100446a0db5b3b0a5bc5d938656c5

**Comment by kyriediculous** [comment]
if you haven't claimed for over 100 rounds the explorer will divide up those transactions and batch them together. 

I believe the explorer currently batches per 50 rounds to play better into miner economics.

**Comment by yondonfu** [comment]
This should no longer be an issue because users no longer after claim earnings for each individual round (earnings from all rounds are automatically claimed). See [LIP-36](https://github.com/livepeer/LIPs/blob/master/LIPs/LIP-36.md) and [LIP-52](https://github.com/livepeer/LIPs/blob/master/LIPs/LIP-52.md).
