### ISSUE TITLE
Transcoder fee vs. broadcaster's max price per segment

### ISSUE THREAD

**Issue by yondonfu** [livepeer/protocol#55]
Currently, the price per segment of a job is always the transcoder's fee. As a result, even if the broadcaster's max price per segment is greater than the transcoder fee, the transcoder will still only earn the fee it originally charged.

In this case, the broadcaster benefits because it is always charged the lowest fees, but the transcoder loses out on additional returns if the broadcaster is willing to pay more i.e. (broadcaster's max price per segment > transcoder's fee).

At first glance, I think the current design makes sense because transcoders set their fee based upon what they believe the minimum compensation for their work should be. Thus, as long as the transcoder receives this minimum compensation, it would be happy. Opening this up for future discussion though

**Comment by dob** [comment]
**Pro's for paying MaxPricePerSegment**

* You always pay a predictable fee, and it's not subject to the whim of which transcoder you get assigned to.
* In the broadcaster's mind the tradeoff is availability vs price. This doesn't fit perfectly into our protocol right now because we only assign one transcoder...but when we figure out the way to seamlessly switch between a bunch of candidates, paying a higher price would give you more consistent service.
* If we end up having jobs that contain multiple profiles, then they can be split across transcoders. It's probably simpler mentally for the broadcaster to just have a common price/gas offered that gets paid in total than to have to calculate it separately for every participating transcoder. I'm following the Ethereum model here.
* Similarly, if we ever figured out how to securely let transcoders compete for the job in near real time (by using an offchain scaling solution like Plasma), then I like the Ethereum model where transcoders would want to get better paying jobs before lower paying jobs.

**The Con's Are**

* Higher price is paid than what transcoder was willing to accept. Network becomes more expensive on average for the broadcaster than it needs to be.

**Comment by yondonfu** [comment]
Done. We are going with paying maxPricePerSegment now
