### ISSUE TITLE
Transcoder shouldn't be able to update their pending fees/price immediately before new round

### ISSUE THREAD

**Issue by dob** [livepeer/protocol#62]
There needs to be a period of time where delegators can review a transcoders fees when they aren't subject to change. Otherwise there is an attack where transcoders advertise great rates, and then switch them at the last minute before being elected in.

I think the simplest temporary implementation might be that the `transcoder()` function throws if you're within `transcoderFreezeBlocks` of the start of the next round. Perhaps this is a couple hours worth? It's not great UX though.

The other option is that this is just defended against socially. If people notice this happening, then they delegate away, and we don't need to update the implementation. 

Finally, people could set a client side flag that says that if a transcoder changes the rates beyond a certain threshold, their client automatically watches and unbonds.

**Comment by yondonfu** [comment]
Re: client side flag - this works if the delegator participates in the protocol using a node, but not if it participates via a dapp unless the delegator allows the dapp to sign transactions on its behalf

Re: social defense - this essentially encourages delegators to be vigilant and to either consistently   monitor transcoders or use some kind of notification service to alert them when a transcoder's rates change. But, a transcoder could always time the change so that delegators have a low probability of being able to move their bond elsewhere before the start of the next round. In this case, delegators could always losing out on a round of fees/rewards since they wouldn't move their bond until the next round and they won't be eligible for the fees/rewards for their new transcoder until the round after that

I'm leaning towards the first solution you described and adding some kind of lock period during the round such that transcoders are unable to perform any actions i.e. update rates, join the transcoder pool, etc. During the lock period, only delegators can perform bond/unbond actions. 

Perhaps we don't need to introduce a specific parameter and instead the second half the round is locked and the condition would look like this?

`block.number - currentRoundStartBlock() <= roundLength / 2`

So if a round is say a week, the first half of the week transcoders join/leave the pool and set their rates and the second half of the week delegators make decisions about who to bond to with full information
