### ISSUE TITLE
ERC23 Transfer Fallback Support?

### ISSUE THREAD

**Issue by dob** [livepeer/protocol#71]
What do you all think about adding [ERC23 support](https://github.com/ethereum/EIPs/issues/223) to the LivepeerToken contract so that users don't lose token if they accidentally send it to the contract address?

[This video](https://www.youtube.com/watch?v=GS62VNyPVHs&feature=youtu.be) does a good job of explaining it, and it seems like it's only adding an additional method + interface in order to add this protection. There will be extra gas for using the transfer function however, since it always has to check whether it's a contract that it's transfering to.

**Comment by yondonfu** [comment]
Flipped through the proposal - I like that it would eliminate the need for the `approve` and `transferFrom` pattern that we currently use for bonding and depositing in addition to preventing users from losing tokens if they accidentally send it to a contract address. However, forcing contracts to implement the token receiver interface in order to receive LivepeerToken doesn't seem ideal from an adoption point of view at least in the near term since no major wallets or multisig contracts currently support ERC223. Transfers to any non-Livepeer contracts would fail until a new version is re-deployed that implements the token receiver interface.

**Comment by dob** [comment]
I see...I was originally thinking that we could just implement it in our
own token contract and bonding contract to add the failsafe for the most
common case...but I see how that would make it impossible for other
contracts to actually accept the token unless they implemented the
standard. Maybe we hold off on this until it's more mature.
