### ISSUE TITLE
Need check to prevent transcoders from claiming the same segments again

### ISSUE THREAD

**Issue by yondonfu** [livepeer/protocol#99]
There isn't anything stopping a transcoder from claiming the same range of segments multiple times right now.

**Comment by dob** [comment]
yikes, very good catch. finding an efficient solution for this might be tough...will think about it. One idea is make it a slashing condition and incentivize fishermen to watch for it.

**Comment by ericxtang** [comment]
Can we introduce an uint32 called `claimedSegs` in Job, and use it as a bitmap to mark which segments have been claimed?

**Comment by dob** [comment]
Currently, we enforce that each claim contains a continuous range of segments. We could open up a fishing/slashing transaction called `claimedDuplicateSegments()` that allows a watcher to submit a segment number which was claimed twice, and two claim ids. The function could easily check if that segment was indeed claimed twice, and if so enact the slashing condition and reward.

Going forward, an additional enhancement here would be to allow transcoders to claim multiple segment ranges in a single transaction, so they don't need multiple claims if they receive a few missing segments. The format could be:

`claim(# of segments claimed, [range0_start, range0_end, range1_start, range1_end, ...)`

The protocol could trust that the # of claimed segments was correct and wouldn't need to do any checks/math on the ranges. That could be done offchain by watchers/fishermen. We would have to add an additional slash condition for `incorrectNumberOfSegmentsClaimed()` which compare the claimed # of segments to the number in the ranges provided. And then the same slashing condition mentioned above for `duplicateClaimedSegment()` logic would need to be updated to support looping through the ranges rather than just checking one range. 

Gas limits would be a consideration for claiming, looping, and slashing. I think it's fair to say that unless a broadcaster is delivering continuous ranges of segments for their stream, it won't be profitable for the transcoder to bother taking the job.

**Comment by yondonfu** [comment]
The double claim segment slashing condition was added in #114. Leaving this issue open to keep track of the possible future enhancements for claiming multiple segment ranges in a single transaction but removing it from the pre-audit milestone

**Comment by yondonfu** [comment]
Closing this issue because the protocol no longer involves a commitment step for claiming segments.
